# Generated by Django 4.2.3 on 2023-07-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('physical_location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedGovernorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('date_fitted', models.DateField()),
                ('expiry_date', models.DateField()),
                ('certificate_status', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.company')),
            ],
        ),
    ]
