# Generated by Django 4.2.3 on 2023-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedgovernorcertificate',
            name='expiry_date',
            field=models.DateField(editable=False),
        ),
    ]
